# build stage
FROM python:3.12 AS builder
WORKDIR /app
COPY requirements.txt . 
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

# RUN Time
FROM python:3.12-slim
WORKDIR /app
COPY --from=builder /install /user/local 
COPY app.py .
CMD ["python", "app.py"]

